config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/guests', to: redirect('/guests.html')

  root 'groups#index'

  resources :welcome, only: :index
  resources :groups do
    resources :documents, only: %i[create destroy], module: 'groups'
    resources :messages, only: :create, module: 'groups'
    resources :questions, only: %i[index show create], module: 'groups' do
      resources :answers, only: %i[create], module: 'questions'
    end

    post :join, on: :collection
  end
  resources :articles, only: %i[index new create edit update show]
  resources :users, only: %i[show edit update]
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :author, class_name: '::User'
  has_many :group_users, class_name: 'Group::User', dependent: :destroy
  has_many :users, through: :group_users
  has_many :documents, class_name: 'Group::Document', dependent: :destroy
  has_many :questions, class_name: 'Group::Question', dependent: :destroy
  has_many :messages, -> { sorted }, class_name: 'Group::Message', dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  before_save :set_token
  after_commit :add_author_to_users, on: :create

  has_one_attached :image

  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end

  private

  def set_token
    self.token = JWT.encode(name, ENV.fetch('JWT_SECRET', nil))
  end

  def add_author_to_users
    Group::User.create(user_id: author_id, group_id: id)
  end
end

app/models/group/document.rb
# frozen_string_literal: true

class Group
  class Document < ApplicationRecord
    belongs_to :author, class_name: '::User'
    belongs_to :group

    has_one_attached :file
  end
end

app/models/group/message.rb
# frozen_string_literal: true

class Group
  class Message < ApplicationRecord
    belongs_to :user, class_name: '::User'
    belongs_to :group

    scope :sorted, -> { order(:id) }

    validates :body, presence: true
  end
end

app/models/group/question.rb
# frozen_string_literal: true

class Group
  class Question < ApplicationRecord
    belongs_to :author, class_name: '::User'
    belongs_to :group
    has_many :answers, class_name: 'Group::Question::Answer', dependent: :destroy

    validates :title, presence: true

    has_rich_text :body
  end
end

app/models/group/question/answer.rb
# frozen_string_literal: true

class Group
  class Question
    class Answer < ApplicationRecord
      belongs_to :author, class_name: '::User'
      belongs_to :question, class_name: 'Group::Question'

      has_rich_text :body
    end
  end
end

app/models/group/user.rb
# frozen_string_literal: true

class Group
  class User < ApplicationRecord
    belongs_to :group
    belongs_to :user, class_name: '::User'
  end
end

app/controllers/groups/documents_controller.rb
# frozen_string_literal: true

module Groups
  class DocumentsController < ApplicationController
    def create
      @document = Group::Document.new(create_params)

      authorize @document

      if @document.save
        flash[:notice] = I18n.t('notice.updated')
        redirect_to group_path(@document.group)
      else
        flash[:error] = @document.errors.full_messages
        redirect_to group_path(@document.group)
      end
    end

    def destroy
      @document = Group::Document.find(params[:id])

      authorize @document

      flash[:notice] = I18n.t('notice.delete_document')
      @document.destroy
      redirect_to group_path(@document.group)
    end

    private

    def create_params
      params.require(:group_document).permit(:file).merge(group_id: params[:group_id], author_id: current_user.id)
    end
  end
end

app/controllers/groups/messages_controller.rb
# frozen_string_literal: true

module Groups
  class MessagesController < ApplicationController
    def create
      @message = Group::Message.new(create_params)

      if @message.save
        group = @message.group

        @message.broadcast_append_to @message.group,
                                     target: "group_#{group.id}_messages",
                                     partial: 'groups/messages/message_other_user',
                                     locals: { message: @message }

        @message.broadcast_replace_to [current_user, group],
                                      target: "message-#{@message.id}",
                                      partial: 'groups/messages/message_current_user',
                                      locals: { message: @message }
      end
    end

    private

    def create_params
      params.require(:group_message).permit(:body, :group_id).merge(user_id: current_user.id)
    end
  end
end

app/controllers/groups/questions/answers_controller.rb
# frozen_string_literal: true

module Groups
  module Questions
    class AnswersController < ApplicationController
      # before_action :set_group, only: %i[index show]

      def create
        @answer = Group::Question::Answer.new(create_params)

        authorize @answer

        if @answer.save
          flash[:notice] = I18n.t('notice.add_answer')
        else
          flash[:error] = @answer.errors.full_messages
        end

        redirect_to group_question_path(group_id: @answer.question.group_id, id: @answer.question.id)
      end

      private

      def create_params
        params.require(:group_question_answer).permit(:title, :body).merge(question_id: params[:question_id],
                                                                           author_id: current_user.id)
      end
    end
  end
end

app/controllers/groups/questions_controller.rb
# frozen_string_literal: true

module Groups
  class QuestionsController < ApplicationController
    before_action :set_group, only: %i[index show]

    def index; end

    def show
      @question = Group::Question.find_by(id: params[:id])

      redirect_to root_path, notice: I18n.t('notice.not_found') if @question.blank?
    end

    def create
      @question = Group::Question.new(create_params)

      authorize @question

      if @question.save
        flash[:notice] = I18n.t('notice.add_question')
      else
        flash[:error] = @question.errors.full_messages
      end

      redirect_to group_path(@question.group)
    end

    private

    def create_params
      params.require(:group_question).permit(:title, :body).merge(group_id: params[:group_id],
                                                                  author_id: current_user.id)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :check_token, only: :show

  def index
    return redirect_to welcome_index_path unless current_user.present?

    @q = policy_scope(Group).ransack(params[:q])
    @groups = @q.result.order(:created_at)
  end

  def show
    authorize @group

    @new_message = current_user.messages.build(group: @group)
  end

  def new
    authorize Group.new
  end

  def create
    authorize Group.new

    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = I18n.t('notice.updated')
      redirect_to group_path(@group)
    else
      flash[:error] = @group.errors.full_messages
      render :new
    end
  end

  def edit
    authorize @group
  end

  def update
    authorize @group

    if @group.update(group_params)
      flash[:notice] = I18n.t('notice.updated')
    else
      flash[:error] = @group.errors.full_messages
    end

    redirect_to group_path(@group)
  end

  def destroy
    authorize @group

    @group.destroy

    flash[:notice] = I18n.t('notice.delete_group')
    redirect_to groups_path
  end

  def join
    group = Group.find_by(token: params[:token])
    if group.present?
      record = Group::User.find_or_create_by(user: current_user, group: group)
      flash[:notice] = I18n.t('group.joined') if record.previously_new_record?
      redirect_to group_path(group)
    else
      flash[:alert] = 'Группа не найдена'
      redirect_to groups_path
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :image).merge(author_id: current_user.id)
  end

  def set_group
    @group = Group.find_by(id: params[:id])
    redirect_to root_path, notice: I18n.t('notice.not_found') if @group.blank?
  end

  def check_token
    return if params[:token].blank?
    return if @group.author == current_user

    if params[:token] == @group.token
      Group::User.find_or_create_by(user: current_user, group: @group)
      flash[:notice] = I18n.t('group.joined')
    end
  end
end

app/views/groups/questions/index.html.erb
<div class="flex justify-center mb-[100px]">
  <div class="container w-8/12">
    <div class="flex flex-col items-center gap-4">
      <div>
        <% if @group.image.attached? %>
          <%= image_tag(@group.image, class: 'rounded-full h-[200px] w-[200px] m-4 object-cover border border-gray', alt: 'Изображение группы') %>
        <% else %>
          <%= vite_image_tag 'images/default_group.jpg',
            alt: "Изображение группы",
            class: "h-[200px] w-[200px] rounded-full h-100 w-100 m-4 border object-cover border-gray" %>
        <% end %>
      </div>
      <div class="font-semibold text-3xl text-gray-800">
        <%= @group.name %>
      </div>
      <div class="w-7/12 text-center text-gray-700">
        <%= @group.description %>
      </div>
      <%= render 'groups/show/tokens' %>
      <div class="flex flex-col gap-3 mt-10 w-full">
        <div class="text-xl font-medium mb-2 flex items-center">
          <%= link_to @group.name, group_path(@group), class: 'text-yellow-500 hover:text-yellow-600', data: { turbo: false } %>
          <span class="material-icons text-gray-700">arrow_right_alt</span>
          <span class="text-gray-700">Вопросы и ответы</span>
        </div>
        <div class="flex gap-3 flex-wrap">
          <% @group.questions.order(:created_at).limit(4).each do |question| %>
            <div class="flex flex-col w-full">
              <div class="text-xl">
                <%= link_to question.title, group_question_path(group_id: @group.id, id: question.id ), class: 'text-gray-700 hover:text-yellow-600', data: { turbo: false } %>
              </div>
              <div class="flex justify-between">
                <div class="text-sm">
                  <% if question.answers.blank? %>
                    Нет ответов
                  <% else %>
                    <%= t('answers', count: question.answers.count) %>
                  <% end %>
                </div>
                <div>
                  <span class="text-gray-700">Задал</span>
                   <span class="text-sm text-yellow-500 hover:text-yellow-600"><%= question.author.short_name %> </span>
                  <span class="text-gray-700"><%= I18n.l(question.created_at, format: :custom)%></span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/questions/show.html.erb
<div class="flex justify-center mb-[100px]">
  <div class="container w-8/12">
    <div class="flex flex-col items-center gap-4">
      <div>
        <% if @group.image.attached? %>
          <%= image_tag(@group.image, class: 'rounded-full h-[200px] w-[200px] m-4 object-cover border border-gray', alt: 'Изображение группы') %>
        <% else %>
          <%= vite_image_tag 'images/default_group.jpg',
            alt: "Изображение группы",
            class: "h-[200px] w-[200px] rounded-full h-100 w-100 m-4 border object-cover border-gray" %>
        <% end %>
      </div>
      <div class="font-semibold text-3xl text-gray-800">
        <%= @group.name %>
      </div>
      <div class="w-7/12 text-center text-gray-700">
        <%= @group.description %>
      </div>
      <%= render 'groups/show/tokens' %>
      <div class="flex flex-col gap-3 mt-10 w-full">
        <div class="text-xl font-medium mb-2 flex items-center">
          <%= link_to @group.name, group_path(@group), class: 'text-yellow-500 hover:text-yellow-600', data: { turbo: false } %>
          <span class="material-icons text-gray-700">arrow_right_alt</span>
          <%= link_to 'Вопросы и ответы', group_questions_path(group_id: @group.id), class: 'text-yellow-500 hover:text-yellow-600', data: { turbo: false } %>
          <span class="material-icons text-gray-700">arrow_right_alt</span>
          <span class="text-gray-700">Вопрос №<%= @question.id %></span>
        </div>
        <div class="text-gray-700 font-extrabold text-3xl mb-4">
          <%= @question.title %>
        </div>
        <div class="flex justify-start items-center gap-3">
          <div>
            <% if @question.author.avatar.attached? %>
              <%= image_tag(@question.author.avatar, class: 'h-42 rounded-full w-[50px] h-[50px] border border-yellow-300 object-cover', alt: 'Аватарка') %>
            <% else %>
              <%= vite_image_tag default_avatar_name(@question.author), alt: "Аватарка", class: "h-42 rounded-full w-[50px] h-[50px] border border-yellow-300 object-cover" %>
            <% end %>
          </div>
          <div>
            <%= @question.author.short_name %>, <span class="text-gray-500"><%= I18n.l(@question.created_at, format: :custom)%></span>
          </div>
        </div>
        <div>
          <%= @question.body %>
        </div>
        <div class="border-b pb-2 mb-4">
          Обсуждение 
          <% if @question.answers.present?  %>
            <span class="text-gray-600"><%= "(#{@question.answers.count})" %></span>
          <% end %>
        </div>
        <% @question.answers.each do |answer| %>
          <div class="flex justify-between">
            <div class="font-semibold text-sm">
              <%= answer.author.short_name %>
            </div>
            <div class="text-gray-500">
              <%= I18n.l(answer.created_at, format: :custom)%>
            </div>
          </div>
          <div class="flex justify-start gap-4 border-b pb-4">
            <div>
              <% if answer.author.avatar.attached? %>
                <%= image_tag(answer.author.avatar, class: 'h-42 rounded-full w-[40px] h-[40px] border border-yellow-300 object-cover', alt: 'Аватарка') %>
              <% else %>
                <%= vite_image_tag default_avatar_name(answer.author), alt: "Аватарка", class: "h-42 rounded-full w-[40px] h-[40px] border border-yellow-300 object-cover" %>
              <% end %>
            </div>
            <div>
              <%= answer.body %>
            </div>
          </div>
        <% end %>
        <div class="w-7/12">
          <%= form_for Group::Question::Answer.new, url: group_question_answers_path(question_id: @question.id), html: { multipart: true }, data: { turbo: false } do |f| %>
            <div class="lg:col-span-2">
              <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
                <div class="md:col-span-5">
                  <%= f.label :body, class: 'text-xl'%>
                  <%= f.rich_text_area :body, class: ' h-[200px]' %>
                </div>
                <div class="md:col-span-5 text-right">
                  <div class="inline-flex items-end">
                    <%= f.submit t('links.send_answer'), class: 'cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>