config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/guests', to: redirect('/guests.html')

  root 'groups#index'

  resources :welcome, only: :index
  resources :groups do
    resources :documents, only: %i[create destroy], module: 'groups'
    resources :messages, only: :create, module: 'groups'
    resources :questions, only: %i[index show create], module: 'groups' do
      resources :answers, only: %i[create], module: 'questions'
    end

    post :join, on: :collection
  end
  resources :articles, only: %i[index new create edit update show]
  resources :users, only: %i[show edit update]
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :author, class_name: '::User'
  has_many :group_users, class_name: 'Group::User', dependent: :destroy
  has_many :users, through: :group_users
  has_many :documents, class_name: 'Group::Document', dependent: :destroy
  has_many :questions, class_name: 'Group::Question', dependent: :destroy
  has_many :messages, -> { sorted }, class_name: 'Group::Message', dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  before_save :set_token
  after_commit :add_author_to_users, on: :create

  has_one_attached :image

  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end

  private

  def set_token
    self.token = JWT.encode(name, ENV.fetch('JWT_SECRET', nil))
  end

  def add_author_to_users
    Group::User.create(user_id: author_id, group_id: id)
  end
end

app/models/group/document.rb
# frozen_string_literal: true

class Group
  class Document < ApplicationRecord
    belongs_to :author, class_name: '::User'
    belongs_to :group

    has_one_attached :file
  end
end

app/models/group/message.rb
# frozen_string_literal: true

class Group
  class Message < ApplicationRecord
    belongs_to :user, class_name: '::User'
    belongs_to :group

    scope :sorted, -> { order(:id) }

    validates :body, presence: true
  end
end

app/models/group/question.rb
# frozen_string_literal: true

class Group
  class Question < ApplicationRecord
    belongs_to :author, class_name: '::User'
    belongs_to :group
    has_many :answers, class_name: 'Group::Question::Answer', dependent: :destroy

    validates :title, presence: true

    has_rich_text :body
  end
end

app/models/group/question/answer.rb
# frozen_string_literal: true

class Group
  class Question
    class Answer < ApplicationRecord
      belongs_to :author, class_name: '::User'
      belongs_to :question, class_name: 'Group::Question'

      has_rich_text :body
    end
  end
end

app/models/group/user.rb
# frozen_string_literal: true

class Group
  class User < ApplicationRecord
    belongs_to :group
    belongs_to :user, class_name: '::User'
  end
end

app/controllers/groups/documents_controller.rb
# frozen_string_literal: true

module Groups
  class DocumentsController < ApplicationController
    def create
      @document = Group::Document.new(create_params)

      authorize @document

      if @document.save
        flash[:notice] = I18n.t('notice.updated')
        redirect_to group_path(@document.group)
      else
        flash[:error] = @document.errors.full_messages
        redirect_to group_path(@document.group)
      end
    end

    def destroy
      @document = Group::Document.find(params[:id])

      authorize @document

      flash[:notice] = I18n.t('notice.delete_document')
      @document.destroy
      redirect_to group_path(@document.group)
    end

    private

    def create_params
      params.require(:group_document).permit(:file).merge(group_id: params[:group_id], author_id: current_user.id)
    end
  end
end

app/controllers/groups/messages_controller.rb
# frozen_string_literal: true

module Groups
  class MessagesController < ApplicationController
    def create
      @message = Group::Message.new(create_params)

      if @message.save
        group = @message.group

        @message.broadcast_append_to @message.group,
                                     target: "group_#{group.id}_messages",
                                     partial: 'groups/messages/message_other_user',
                                     locals: { message: @message }

        @message.broadcast_replace_to [current_user, group],
                                      target: "message-#{@message.id}",
                                      partial: 'groups/messages/message_current_user',
                                      locals: { message: @message }
      end
    end

    private

    def create_params
      params.require(:group_message).permit(:body, :group_id).merge(user_id: current_user.id)
    end
  end
end

app/controllers/groups/questions/answers_controller.rb
# frozen_string_literal: true

module Groups
  module Questions
    class AnswersController < ApplicationController
      # before_action :set_group, only: %i[index show]

      def create
        @answer = Group::Question::Answer.new(create_params)

        authorize @answer

        if @answer.save
          flash[:notice] = I18n.t('notice.add_answer')
        else
          flash[:error] = @answer.errors.full_messages
        end

        redirect_to group_question_path(group_id: @answer.question.group_id, id: @answer.question.id)
      end

      private

      def create_params
        params.require(:group_question_answer).permit(:title, :body).merge(question_id: params[:question_id],
                                                                           author_id: current_user.id)
      end
    end
  end
end

app/controllers/groups/questions_controller.rb
# frozen_string_literal: true

module Groups
  class QuestionsController < ApplicationController
    before_action :set_group, only: %i[index show]

    def index; end

    def show
      @question = Group::Question.find_by(id: params[:id])

      redirect_to root_path, notice: I18n.t('notice.not_found') if @question.blank?
    end

    def create
      @question = Group::Question.new(create_params)

      authorize @question

      if @question.save
        flash[:notice] = I18n.t('notice.add_question')
      else
        flash[:error] = @question.errors.full_messages
      end

      redirect_to group_path(@question.group)
    end

    private

    def create_params
      params.require(:group_question).permit(:title, :body).merge(group_id: params[:group_id],
                                                                  author_id: current_user.id)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :check_token, only: :show

  def index
    return redirect_to welcome_index_path unless current_user.present?

    @q = policy_scope(Group).ransack(params[:q])
    @groups = @q.result.order(:created_at)
  end

  def show
    authorize @group

    @new_message = current_user.messages.build(group: @group)
  end

  def new
    authorize Group.new
  end

  def create
    authorize Group.new

    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = I18n.t('notice.updated')
      redirect_to group_path(@group)
    else
      flash[:error] = @group.errors.full_messages
      render :new
    end
  end

  def edit
    authorize @group
  end

  def update
    authorize @group

    if @group.update(group_params)
      flash[:notice] = I18n.t('notice.updated')
    else
      flash[:error] = @group.errors.full_messages
    end

    redirect_to group_path(@group)
  end

  def destroy
    authorize @group

    @group.destroy

    flash[:notice] = I18n.t('notice.delete_group')
    redirect_to groups_path
  end

  def join
    group = Group.find_by(token: params[:token])
    if group.present?
      record = Group::User.find_or_create_by(user: current_user, group: group)
      flash[:notice] = I18n.t('group.joined') if record.previously_new_record?
      redirect_to group_path(group)
    else
      flash[:alert] = 'Группа не найдена'
      redirect_to groups_path
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :image).merge(author_id: current_user.id)
  end

  def set_group
    @group = Group.find_by(id: params[:id])
    redirect_to root_path, notice: I18n.t('notice.not_found') if @group.blank?
  end

  def check_token
    return if params[:token].blank?
    return if @group.author == current_user

    if params[:token] == @group.token
      Group::User.find_or_create_by(user: current_user, group: @group)
      flash[:notice] = I18n.t('group.joined')
    end
  end
end

app/views/groups/show/_chat.html.erb
<%= turbo_stream_from @group %>
<%= turbo_stream_from [current_user, @group] %>

<h4 class="text-2xl font-medium mt-5 mb-4">
  Чат
</h4>
<div class="flex justify-center border border-gray-300 p-4 rounded-lg">
  <div class="w-full">
    <div class="flex flex-col h-96 justify-between">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="group-container">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="group_<%= @group.id %>_messages">
            <%= render partial: "groups/messages/message", collection: @group.messages, locals: { user: current_user } %>
        </div>
      </div>
    </div>
    <%= form_with model: @new_message, url: group_messages_path(group_id: @group.id), data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" }  do |f| %>
      <div class="rounded-md shadow-sm -space-y-px mt-4">
        <%= f.text_field :body, required: true, placeholder: "Ваше сообщение", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        <%= f.hidden_field :group_id, value: @group.id %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show/_document_modal.html.erb
<div id="static-modal-document" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full ml-[64px]">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <div class="relative rounded-lg shadow flex flex-col items-center border-2 border-yellow-300 bg-white">
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t w-full">
        <h3 class="text-xl font-semibold text-gray-600">
          Создать документ
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-yellow-200 hover:text-white rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="static-modal-document">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <div class="w-9/12 mb-4 mt-4">
        <%= form_for Group::Document.new, url: group_documents_path(@group), html: { multipart: true }, data: { turbo: false } do |f| %>
          <div class="lg:col-span-2">
            <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
              <div class="md:col-span-5">
                <%= f.label :file %>
                <%= f.file_field :file, class: 'block p-2 w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none' %>
              </div>
              <div class="md:col-span-5 text-right">
                <div class="inline-flex items-end">
                  <%= f.submit t('links.save'), class: 'cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show/_documents.html.erb
<div class="flex flex-col gap-3 mt-5 flex-wrap">
  <h4 class="text-2xl font-medium  mb-2">
    Документы
  </h4>
  <div class="flex gap-3 flex-wrap">
    <% @group.documents.each do |document| %>
      <div class="flex flex-col items-center text-gray-700">
        <span class="material-icons text-gray-600 text-4xl">description</span>
        <%= link_to document.file.filename, rails_blob_path(document.file), class: 'w-24 text-center break-words hover:text-yellow-500'%>
        <% if @group.author == current_user ||  document.author == current_user %>
          <%= button_to group_document_path(group_id: @group.id, id: document.id), method: :delete, data: { controller: "delete", action: "click->delete#confirmDelete" }  do %>
            <span class="material-icons text-gray-600 hover:text-gray-700 cursor-pointer">delete</span>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="flex items-center">
      <button data-modal-target="static-modal-document" data-modal-toggle="static-modal-document" class="cursor-pointer 
      text-white bg-yellow-500 hover:bg-yellow-600 font-medium rounded-full text-sm h-6 w-6 flex items-center 
      justify-center">
        <span class="material-icons">add</span>
      </button>
    </div>
  </div>
</div>

app/views/groups/show/_question_modal.html.erb
<div id="static-modal-question" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full ml-[64px]">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <div class="relative rounded-lg shadow flex flex-col items-center border-2 border-yellow-300 bg-white">
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t w-full">
        <h3 class="text-xl font-semibold text-gray-600">
          Добавить обсуждение
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-yellow-200 hover:text-white rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="static-modal-question">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <div class="w-9/12 mb-4 mt-4">
        <%= form_for Group::Question.new, url: group_questions_path(@group), html: { multipart: true }, data: { turbo: false } do |f| %>
          <div class="lg:col-span-2">
            <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
              <div class="md:col-span-5">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'h-10 border border-gray-200 text-gray-600 mt-1 rounded-lg px-4 w-full' %>
              </div>
              <div class="md:col-span-5">
                <%= f.label :body %>
                <%= f.rich_text_area :body, class: ' h-[200px]' %>
              </div>
              <div class="md:col-span-5 text-right">
                <div class="inline-flex items-end">
                  <%= f.submit t('links.save'), class: 'cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show/_questions.html.erb
<div class="flex flex-col gap-3 mt-5 w-full">
  <h4 class="text-2xl font-medium mb-2">
    Вопросы и ответы
  </h4>
  <div class="flex flex-col gap-3 flex-wrap ml-2">
    <% @group.questions.order(:created_at).limit(4).each do |question| %>
      <div class="flex flex-col text-gray-700 gap-3">
        <div class="text-sm flex justify-start">
          <div class="w-[230px] border-r-2 border-yellow-300 ">
            <span>Автор:</span>
            <span class="font-semibold pr-2"><%= question.author.short_name %></span>
          </div>
          <%= link_to group_question_path(group_id: @group.id, id: question.id ), data: { turbo: false } do %>
            <span class="hover:text-yellow-500 hover:font-bold ml-4"><%= question.title %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show/_questions_footer.html.erb
<div class="flex justify-between gap-3 mt-4">
  <%= link_to 'все вопросы', group_questions_path(group_id: @group.id), class: 'hover:text-yellow-500 font-bold text-gray-700', data: { turbo: false } %>
  <button data-modal-target="static-modal-question" data-modal-toggle="static-modal-question" class="cursor-pointer">
    <div class="flex gap-2">
          <span class="material-icons text-white bg-yellow-500 hover:bg-yellow-600 font-medium rounded-full text-sm h-6 w-6 flex items-center 
           justify-center">add</span>
      <span class="text-sm text-gray-700 hover:text-yellow-500">Добавить обсуждение</span>
    </div>
  </button>
</div>

app/views/groups/show/_tokens.html.erb
<div class="flex gap-2">
  <div class="relative" data-controller="clipboard">
    <p data-clipboard-target="textElement" id="group-token" class="hidden"><%= @group.token %></p>
    <button data-clipboard-target="copyButton" data-action="click->clipboard#copy" id="token-copy-button" class="cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center flex items-center gap-2">
      <span>Скопировать токен</span>
      <span class="material-icons">share</span>
    </button>
  </div>
  <div class="relative" data-controller="clipboard">
    <p data-clipboard-target="textElement" id="group-url-with-token" class="hidden"><%= "#{request.base_url}/groups/#{@group.id}?token=#{@group.token}" %></p>
    <button data-clipboard-target="copyButton" data-action="click->clipboard#copy" id="token-url-copy-button" class="cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center flex items-center gap-2">
      <span>Скопировать ссылку</span>
      <span class="material-icons">link</span>
    </button>
  </div>
</div>
</div>

app/views/groups/show/_users.html.erb
<div class="flex flex-col gap-3 mt-5">
  <h4 class="text-2xl font-medium mb-2">
    Участники
  </h4>
  <div class="flex gap-3 flex-wrap w-9/12 ml-2">
    <% @group.users.each do |user| %>
      <div class="flex flex-col items-center text-gray-700">
        <%= link_to user_path(user) do %>
          <% if user.avatar.attached? %>
            <%= image_tag(user.avatar, class: 'rounded-full h-[50px] w-[50px] cursor-pointer object-cover border border-yellow-300', alt: 'Аватар пользователя') %>
          <% else %>
            <%= vite_image_tag default_avatar_name(user), alt: "Аватарка", class: "border border-yellow-300 rounded-full h-[50px] w-[50px] cursor-pointer object-cover" %>
          <% end %>
        <% end %>
        <div class="mt-2">
          <%= user.first_name %>
        </div>
        <div>
          <%= user.surname %>
        </div>
      </div>
    <% end %>
  </div>
</div>