config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/guests', to: redirect('/guests.html')

  root 'groups#index'

  resources :welcome, only: :index
  resources :groups do
    resources :documents, only: %i[create destroy], module: 'groups'
    resources :messages, only: :create, module: 'groups'
    resources :questions, only: %i[index show create], module: 'groups' do
      resources :answers, only: %i[create], module: 'questions'
    end

    post :join, on: :collection
  end
  resources :articles, only: %i[index new create edit update show]
  resources :users, only: %i[show edit update]
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :author, class_name: '::User'
  has_many :group_users, class_name: 'Group::User', dependent: :destroy
  has_many :users, through: :group_users
  has_many :documents, class_name: 'Group::Document', dependent: :destroy
  has_many :questions, class_name: 'Group::Question', dependent: :destroy
  has_many :messages, -> { sorted }, class_name: 'Group::Message', dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  before_save :set_token
  after_commit :add_author_to_users, on: :create

  has_one_attached :image

  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end

  private

  def set_token
    self.token = JWT.encode(name, ENV.fetch('JWT_SECRET', nil))
  end

  def add_author_to_users
    Group::User.create(user_id: author_id, group_id: id)
  end
end

app/models/group/document.rb
# frozen_string_literal: true

class Group
  class Document < ApplicationRecord
    belongs_to :author, class_name: '::User'
    belongs_to :group

    has_one_attached :file
  end
end

app/models/group/message.rb
# frozen_string_literal: true

class Group
  class Message < ApplicationRecord
    belongs_to :user, class_name: '::User'
    belongs_to :group

    scope :sorted, -> { order(:id) }

    validates :body, presence: true
  end
end

app/models/group/question.rb
# frozen_string_literal: true

class Group
  class Question < ApplicationRecord
    belongs_to :author, class_name: '::User'
    belongs_to :group
    has_many :answers, class_name: 'Group::Question::Answer', dependent: :destroy

    validates :title, presence: true

    has_rich_text :body
  end
end

app/models/group/question/answer.rb
# frozen_string_literal: true

class Group
  class Question
    class Answer < ApplicationRecord
      belongs_to :author, class_name: '::User'
      belongs_to :question, class_name: 'Group::Question'

      has_rich_text :body
    end
  end
end

app/models/group/user.rb
# frozen_string_literal: true

class Group
  class User < ApplicationRecord
    belongs_to :group
    belongs_to :user, class_name: '::User'
  end
end

app/controllers/groups/documents_controller.rb
# frozen_string_literal: true

module Groups
  class DocumentsController < ApplicationController
    def create
      @document = Group::Document.new(create_params)

      authorize @document

      if @document.save
        flash[:notice] = I18n.t('notice.updated')
        redirect_to group_path(@document.group)
      else
        flash[:error] = @document.errors.full_messages
        redirect_to group_path(@document.group)
      end
    end

    def destroy
      @document = Group::Document.find(params[:id])

      authorize @document

      flash[:notice] = I18n.t('notice.delete_document')
      @document.destroy
      redirect_to group_path(@document.group)
    end

    private

    def create_params
      params.require(:group_document).permit(:file).merge(group_id: params[:group_id], author_id: current_user.id)
    end
  end
end

app/controllers/groups/messages_controller.rb
# frozen_string_literal: true

module Groups
  class MessagesController < ApplicationController
    def create
      @message = Group::Message.new(create_params)

      if @message.save
        group = @message.group

        @message.broadcast_append_to @message.group,
                                     target: "group_#{group.id}_messages",
                                     partial: 'groups/messages/message_other_user',
                                     locals: { message: @message }

        @message.broadcast_replace_to [current_user, group],
                                      target: "message-#{@message.id}",
                                      partial: 'groups/messages/message_current_user',
                                      locals: { message: @message }
      end
    end

    private

    def create_params
      params.require(:group_message).permit(:body, :group_id).merge(user_id: current_user.id)
    end
  end
end

app/controllers/groups/questions/answers_controller.rb
# frozen_string_literal: true

module Groups
  module Questions
    class AnswersController < ApplicationController
      # before_action :set_group, only: %i[index show]

      def create
        @answer = Group::Question::Answer.new(create_params)

        authorize @answer

        if @answer.save
          flash[:notice] = I18n.t('notice.add_answer')
        else
          flash[:error] = @answer.errors.full_messages
        end

        redirect_to group_question_path(group_id: @answer.question.group_id, id: @answer.question.id)
      end

      private

      def create_params
        params.require(:group_question_answer).permit(:title, :body).merge(question_id: params[:question_id],
                                                                           author_id: current_user.id)
      end
    end
  end
end

app/controllers/groups/questions_controller.rb
# frozen_string_literal: true

module Groups
  class QuestionsController < ApplicationController
    before_action :set_group, only: %i[index show]

    def index; end

    def show
      @question = Group::Question.find_by(id: params[:id])

      redirect_to root_path, notice: I18n.t('notice.not_found') if @question.blank?
    end

    def create
      @question = Group::Question.new(create_params)

      authorize @question

      if @question.save
        flash[:notice] = I18n.t('notice.add_question')
      else
        flash[:error] = @question.errors.full_messages
      end

      redirect_to group_path(@question.group)
    end

    private

    def create_params
      params.require(:group_question).permit(:title, :body).merge(group_id: params[:group_id],
                                                                  author_id: current_user.id)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :check_token, only: :show

  def index
    return redirect_to welcome_index_path unless current_user.present?

    @q = policy_scope(Group).ransack(params[:q])
    @groups = @q.result.order(:created_at)
  end

  def show
    authorize @group

    @new_message = current_user.messages.build(group: @group)
  end

  def new
    authorize Group.new
  end

  def create
    authorize Group.new

    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = I18n.t('notice.updated')
      redirect_to group_path(@group)
    else
      flash[:error] = @group.errors.full_messages
      render :new
    end
  end

  def edit
    authorize @group
  end

  def update
    authorize @group

    if @group.update(group_params)
      flash[:notice] = I18n.t('notice.updated')
    else
      flash[:error] = @group.errors.full_messages
    end

    redirect_to group_path(@group)
  end

  def destroy
    authorize @group

    @group.destroy

    flash[:notice] = I18n.t('notice.delete_group')
    redirect_to groups_path
  end

  def join
    group = Group.find_by(token: params[:token])
    if group.present?
      record = Group::User.find_or_create_by(user: current_user, group: group)
      flash[:notice] = I18n.t('group.joined') if record.previously_new_record?
      redirect_to group_path(group)
    else
      flash[:alert] = 'Группа не найдена'
      redirect_to groups_path
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :image).merge(author_id: current_user.id)
  end

  def set_group
    @group = Group.find_by(id: params[:id])
    redirect_to root_path, notice: I18n.t('notice.not_found') if @group.blank?
  end

  def check_token
    return if params[:token].blank?
    return if @group.author == current_user

    if params[:token] == @group.token
      Group::User.find_or_create_by(user: current_user, group: @group)
      flash[:notice] = I18n.t('group.joined')
    end
  end
end

app/views/groups/_card.html.erb
<div class="flex flex-col items-start border border-gray-300 rounded rounded-xl w-[440px] gap-2">
  <div class="flex items-center">
    <% if group.image.attached? %>
      <%= image_tag(group.image, class: 'rounded-full h-28  w-28 m-4 object-cover border border-gray', alt: 'Изображение группы') %>
    <% else %>
      <%= vite_image_tag 'images/default_group.jpg', alt: "Аватарка", class: "rounded-full h-28  w-28 m-4 border object-cover border-gray" %>
    <% end %>
    <div class="text-md text-gray-700 font-semibold">
      <h3><%= group.name %></h3>
    </div>
  </div>
  <div class="ml-4 text-gray-700">
    Участники
  </div>
  <div class="ml-4 mr-4 flex justify-start gap-2 flex-wrap">
    <% group.users.each do |user| %>
      <%= link_to user_path(user) do %>
        <% if user.avatar.attached? %>
          <%= image_tag(user.avatar, class: 'rounded-full h-10  w-10 cursor-pointer object-cover', alt: 'Аватар пользователя', title: user.short_name) %>
        <% else %>
          <%= vite_image_tag default_avatar_name(user), alt: "Аватарка", class: "border border-yellow-300 rounded-full h-10  w-10 cursor-pointer object-cover", title: user.short_name %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="ml-4 mb-4 mt-4">
    <%= link_to t('links.show_group'), group_path(group), data: { turbo: false }, class: 'cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
  </div>
</div>

app/views/groups/_form.html.erb
<div class="p-6 flex items-center justify-center ">
  <div class="">
    <div>
      <div class="bg-white rounded shadow-lg p-4 px-4 mb-6 border border-yellow-300">
        <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3">
          <div class="text-gray-600">
            <p class="font-medium text-lg">
              <%= @group.present? ? 'Редактировать группу' : 'Новая группа' %>
            </p>
          </div>
          <%= form_for @group || Group.new, html: { multipart: true }, data: { turbo: false } do |f| %>
            <div class="lg:col-span-2">
              <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
                <div class="md:col-span-5">
                  <%= f.label :name %>
                  <%= f.text_field :name, class: 'h-10 border border-gray-200 text-gray-600 mt-1 rounded-lg px-4 w-full' %>
                </div>
                <div class="md:col-span-5">
                  <%= f.label :description, class: 'text-gray-700' %>
                  <%= f.text_area :description, class: 'h-10 border border-gray-200 text-gray-600 mt-1 rounded-lg px-4 text-sm w-full h-[200px]' %>
                </div>
                <div class="md:col-span-5">
                  <%= f.label :image %>
                  <%= f.file_field :image, class: 'block p-2 w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none' %>
                </div>
                <div class="md:col-span-5 text-right">
                  <div class="inline-flex items-end">
                    <%= f.submit t('links.save'), class: 'cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>

                  </div>
                </div>
              </div>
              <% if @group.present? %>
                <%= link_to t('links.delete_group'), group_path(@group),
                  method: :delete, class: 'text-red-500', data: { controller: "delete", action: "click->delete#confirmDelete" }  %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_modal.html.erb
<div id="static-modal" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full ml-[64px]">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <div class="relative rounded-lg shadow flex flex-col items-center border-2 border-yellow-300 bg-white">
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t w-full">
        <h3 class="text-xl font-semibold text-gray-600">
          Введите токен
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-yellow-200 hover:text-white rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="static-modal">
          <svg class=" w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <div class="w-9/12 mb-4 mt-4">
        <%= form_with url: join_groups_path, method: :post, local: true do |f| %>
          <div class="lg:col-span-2">
            <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
              <div class="md:col-span-5">
                <%= f.text_field :token, class: 'h-10 border border-gray-200 text-gray-600 mt-1 rounded-lg px-4 w-full' %>
              </div>
              <div class="md:col-span-5 text-right">
                <div class="inline-flex items-end">
                  <%= f.submit 'Присоединиться', class: 'mt-2 cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_modal_share.html.erb
<div id="static-modal" data-modal-backdrop="static" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <div class="relative rounded-lg shadow flex flex-col bg-gray-500 items-center">
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t w-full">
        <h3 class="text-xl font-semibold text-white">
          Введите токен 3242342
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="static-modal">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <div class="w-9/12 mb-4 mt-4">
        <%= form_with url: join_groups_path, method: :post, local: true do |f| %>
          <div class="lg:col-span-2">
            <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
              <div class="md:col-span-5">
                <%= f.text_field :token, class: 'h-10 border border-gray-200 text-gray-600 mt-1 rounded-lg px-4 w-full' %>
              </div>
              <div class="md:col-span-5 text-right">
                <div class="inline-flex items-end">
                  <%= f.submit 'Присоединиться', class: 'mt-2 cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<div class="w-full flex justify-center mt-10">
  <%= render "modal" %>
  <div class="flex flex-col items-center flex-wrap text-center w-10/12 gap-16">
    <div class="w-full">
      <h2 class="text-2xl text-gray-700 font-semibold">Мои группы</h2>
    </div>
    <div class="flex items-center justify-between w-full">
      <div>
        <%= search_form_for @q, url: groups_path, method: :get, html: { class: 'flex items-center max-w-sm mx-auto' } do |f| %>
          <%= f.label :name_cont, 'Search', class: 'sr-only' %>
          <div class="relative w-full">
            <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            </div>
            <%= f.search_field :name_cont,
              class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5",
              placeholder: "Поиск" %>
          </div>
          <button type="submit" class="p-2.5 ms-2 text-sm font-medium text-white rounded-lg focus:ring-4 focus:ring-blue-300 bg-yellow-500 hover:bg-yellow-600">
            <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
            <span class="sr-only">Search</span>
          </button>
        <% end %>
      </div>
      <div>
        <button data-modal-target="static-modal" data-modal-toggle="static-modal" class="cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center" type="button">
          <%= t('links.join_group') %>
        </button>
        <%= link_to t('links.create_group'), new_group_path, class: 'cursor-pointer text-white bg-yellow-500 
                       hover:bg-yellow-600 focus:ring-4 focus:outline-none 
                       focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center' %>
      </div>
    </div>
    <div class="flex flex-wrap justify-center w-full gap-4">
      <% @groups.each do |group| %>
        <%= render "card", group: group %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<div class="flex justify-center mb-[100px]">
  <%= render 'groups/show/document_modal' %>
  <%= render 'groups/show/question_modal' %>
  <div class="container w-8/12">
    <div class="flex flex-col items-center gap-4">
      <div>
        <% if @group.image.attached? %>
          <%= image_tag(@group.image, class: 'rounded-full h-[200px] w-[200px] m-4 object-cover border border-gray', alt: 'Изображение группы') %>
        <% else %>
          <%= vite_image_tag 'images/default_group.jpg',
            alt: "Изображение группы",
            class: "h-[200px] w-[200px] rounded-full h-100 w-100 m-4 border object-cover border-gray" %>
        <% end %>
      </div>
      <div class="font-semibold text-3xl text-gray-800">
        <%= @group.name %>
      </div>
      <div class="w-7/12 text-center text-gray-700">
        <%= @group.description %>
      </div>
      <%= render 'groups/show/tokens' %>
      <%= render 'groups/show/users' %>
      <%= render 'groups/show/documents' %>
      <%= render 'groups/show/questions' %>
      <%= render 'groups/show/questions_footer' %>
      <%= render 'groups/show/chat' %>
      <% if current_user.admin? || @group.author == current_user  %>
        <div class="flex justify-end mt-5 w-7/12">
          <%= link_to t('links.edit_group'), edit_group_path(@group), data: { turbo: false }, class: 'cursor-pointer text-white bg-yellow-500 
            hover:bg-yellow-600 focus:ring-4 focus:outline-none 
            focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center' %>
        </div>
    <% end %>
    </div>
  </div>
</div>